config/routes.rb
Rails.application.routes.draw do
  get 'dashboard', to: 'dashboard#index', as: 'dashboard'
  get 'dashboard/payment_methods', to: 'dashboard#payment_methods', as: 'payment_methods'
  get 'surveys/created', to: 'surveys#created', as: 'created_surveys'
  get 'statistics', to: 'statistics#show', as: 'statistics'
  get 'notifications', to: 'notifications#index', as: 'notifications'
  post 'earn_money', to: 'transactions#create', as: 'earn_money'
  resources :transactions, only: [:index]
  resources :profiles, only: [:show, :edit, :update]
  resources :bank_accounts, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  resources :wallets, only: [:new, :create, :edit, :update, :destroy]
  resources :transactions, only: [:index, :show, :new, :create]
  resources :categories do 
    resources :products do
      resources :surveys do
        resources :responses, only: [:create]
        resources :questions do
          resources :choices
        end
      end
    end
  end
  root 'categories#index'
  get 'home/about_us', to: 'home#about_us'
  get 'home/for_you', to: 'home#for_you'
  get 'home/how_it_works', to: 'home#how_it_works'
  get 'home/why_us', to: 'home#why_us'
  get 'products/show', to: 'products#show'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bank_account.rb
class BankAccount < ApplicationRecord
  belongs_to :user
  validates :bank_name, :account_number, presence: true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :products
    has_many :surveys, through: :products
end

app/models/choice.rb
class Choice < ApplicationRecord
  belongs_to :question
  has_many :responses
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user
end

app/models/opinion.rb
class Opinion < ApplicationRecord
  belongs_to :user
  belongs_to :survey
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :surveys
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
end

app/models/question.rb
# app/models/question.rb
class Question < ApplicationRecord
  belongs_to :survey
  has_many :responses
  has_many :choices, dependent: :destroy
  accepts_nested_attributes_for :choices, allow_destroy: true
end

app/models/response.rb
class Response < ApplicationRecord
    belongs_to :user
    belongs_to :survey
    belongs_to :question
    belongs_to :choice
  end

app/models/survey.rb
class Survey < ApplicationRecord
  belongs_to :user
  belongs_to :product
  belongs_to :category
  has_many :responses, dependent: :destroy
  has_many :questions, inverse_of: :survey, dependent: :destroy
  has_many :transactions
  accepts_nested_attributes_for :questions, allow_destroy: true, reject_if: :all_blank
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :user
  belongs_to :survey

  validates :amount, presence: true
  validates :payment_method, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :profile
  has_many :bank_accounts
  has_many :wallets
  has_many :opinions
  has_one :wallet, dependent: :destroy
  has_one :bank_account, dependent: :destroy
  has_many :responses, dependent: :destroy
  has_many :surveys, through: :responses
  has_many :transactions
  accepts_nested_attributes_for :wallet, allow_destroy: true
  accepts_nested_attributes_for :bank_account, allow_destroy: true

  after_create :create_wallet

  validates :name, presence: true

  private

  def create_wallet
    Wallet.create(user: self, balance: 0.0)
  end
end

app/models/wallet.rb
# app/models/wallet.rb
class Wallet < ApplicationRecord
  belongs_to :user
  
  validates :balance, presence: true, numericality: { greater_than_or_equal_to: 0 }

  def deposit(amount)
    self.balance += amount
    save!
  end

  def withdraw(amount)
    self.balance -= amount
    save!
  end
end

app/controllers/categories_controller.rb
# app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  def index
    @categories = Category.all
    @category = @categories.first
    @products = @category.present? ? @category.products : []
    @product = @products.first if @products.any?
  end

  def show
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to @category, notice: 'Category was successfully created.'
    else
      render :new
    end
  end

  def update
    if @category.update(category_params)
      redirect_to @category, notice: 'Category was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @category.destroy
    redirect_to categories_url, notice: 'Category was successfully destroyed.'
  end
  
  
  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/choices_helper.rb
module ChoicesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/opinions_helper.rb
module OpinionsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/categories/_form.html.erb
<div class="container">
  <h1>New Category</h1>
  <%= form_with(model: category, local: true) do |form| %>
    <% if category.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>
        <ul>
          <% category.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="form-group">
      <%= form.label :name %>
      <%= form.text_field :name, class: 'form-control' %>
    </div>
    <div class="form-group mt-4">
      <%= form.submit 'Create Category', class: 'btn btn-primary' %>
      <%= link_to 'Back', categories_path, class: 'btn btn-secondary text-white' %>
    </div>
  <% end %>
</div>

app/views/categories/_products.html.erb
<!-- app/views/categories/_products.html.erb -->
<%if current_user%>
<% if products.any? %>
  <ul class="list-group">
    <% products.each do |product| %>
      <li class="list-group-item">
        <h1><%= link_to product.name, category_product_path(@category, product), class: 'list-group-item' %> </h1>
      </li>
    <% end %>
  </ul>
<% else %>
  <div class="alert alert-info">No products available for this category.</div>
<% end %>
<%else%>
  <div class="alert alert-info">Please sign in to see all the products</div>
<%end%>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
 <style>
        .category-card, .product-card {
            margin-bottom: 20px;
        }
        .navbar-custom {
            background-color: #333;
        }
        .navbar-custom .navbar-nav .nav-link {
            color: #fff;
        }
        .carousel-inner img {
            width: 100%;
            height: 300px;
        }
        .carousel .carousel-item img {
            filter: brightness(50%); /* Lower percentage = darker image */
        }
    </style>
<!-- app/views/categories/index.html.erb -->
<div class="container mt-4">
  <div id="carouselExampleIndicators" class="carousel slide carousel-border" data-bs-ride="carousel">
      <div class="carousel-inner">
          <div class="carousel-item active">
              <%= image_tag("/img_1.jpg", class: "d-block w-100", alt: "...") %>
          </div>
          <div class="carousel-item">
              <%= image_tag("/img_2.jpg", class: "d-block w-100", alt: "...") %>
          </div>
          <div class="carousel-item">
              <%= image_tag("/img_3.jpg", class: "d-block w-100", alt: "...") %>
          </div>
      </div>
      <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
      </button>
  </div>
  
  <div class="text-center mt-5">
    <h3>Categories we target to survey</h3>
    <p>Some quick example text to build on the card title and make up the bulk of the card's content.</p>
  </div>
  <%if current_user&.admin==true %>
  <%= link_to 'New Category', new_category_path, class: 'btn btn-primary text-white text-white mb-3' %>
  <%end%>
  <div class="d-flex  mt-4">
    <div class="d-flex flex-fill mx-2">
      <% @categories.each do |category| %>
          <%= link_to category.name, category_path(category), class: 'btn btn-outline-secondary mx-1' %>
      <% end %>
    </div>
  </div>
  
  <div class="mt-5">
    <div class="card category-card">
      <div class="card-body">
        <h5 class="card-title">What We Do</h5>
        <h6 class="card-subtitle mb-2 text-muted">Subtitle here</h6>
        <p class="card-text">I'm a thing. But, like most politicians, he promised more than he could deliver. You won't have time for sleeping, soldier, not with all the bed making you'll be doing. Then we'll go with that data file! Hey, you add a one and two zeros to that or we walk! You're going to do his laundry? I've got to find a way to escape.</p>
        <a href="#" class="btn btn-primary text-white">See More</a>
        <a href="#" class="btn btn-secondary text-white">Share</a>
      </div>
    </div>

    <div class="card category-card">
      <div class="card-body">
        <h5 class="card-title">Why Us</h5>
        <h6 class="card-subtitle mb-2 text-muted">Subtitle here</h6>
        <p class="card-text">I'm a thing. But, like most politicians, he promised more than he could deliver. You won't have time for sleeping, soldier, not with all the bed making you'll be doing. Then we'll go with that data file! Hey, you add a one and two zeros to that or we walk! You're going to do his laundry? I've got to find a way to escape.</p>
        <a href="#" class="btn btn-primary text-white">See More</a>
        <a href="#" class="btn btn-secondary text-white">Share</a>
      </div>
    </div>

    <div class="card category-card">
      <div class="card-body">
        <h5 class="card-title">How It Works</h5>
        <h6 class="card-subtitle mb-2 text-muted">Subtitle here</h6>
        <p class="card-text">I'm a thing. But, like most politicians, he promised more than he could deliver. You won't have time for sleeping, soldier, not with all the bed making you'll be doing. Then we'll go with that data file! Hey, you add a one and two zeros to that or we walk! You're going to do his laundry? I've got to find a way to escape.</p>
        <a href="#" class="btn btn-primary text-white">See More</a>
        <a href="#" class="btn btn-secondary text-white">Share</a>
      </div>
    </div>

    <div class="card category-card">
      <div class="card-body">
        <h5 class="card-title">What Is In For You</h5>
        <h6 class="card-subtitle mb-2 text-muted">Subtitle here</h6>
        <p class="card-text">I'm a thing. But, like most politicians, he promised more than he could deliver. You won't have time for sleeping, soldier, not with all the bed making you'll be doing. Then we'll go with that data file! Hey, you add a one and two zeros to that or we walk! You're going to do his laundry? I've got to find a way to escape.</p>
        <a href="#" class="btn btn-primary text-white">See More</a>
        <a href="#" class="btn btn-secondary text-white">Share</a>
      </div>
    </div>
  </div>
</div>

app/views/categories/new.html.erb
>
<%= render 'form', category: @category %>

app/views/categories/show.html.erb
<div class="container mt-5">
  <div class="d-flex justify-content-between align-items-center mb-4">
    <h1 class="display-4"><%= @category.name %></h1>
    <div>
      <%if current_user.admin==true %>
      <%= link_to 'Edit', edit_category_path(@category), class: 'btn btn-warning text-white mr-2' %>
      <%= link_to 'New Product', new_category_product_path(@category), class: 'btn btn-primary text-white text-white' %>
      <%end%>
      <%= link_to 'Back', categories_path, class: 'btn btn-secondary text-white mr-2' %>
    </div>
  </div>

  <h2 class="mt-4">Products</h2>
  <div class="row">
    <% @category.products.each do |product| %>
      <div class="col-md-6 mb-3">
        <div class="card h-100">
          <div class="card-body">
            <h3 class="card-title"><%= link_to product.name, category_product_path(@category, product), class: 'product-link' %></h3>
            <p class="card-text"><%= product.description %></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

<style>
  .product-link {
    color: #007bff;
    text-decoration: none;
  }
  .product-link:hover {
    text-decoration: underline;
  }
</style>